# -*- coding: utf-8 -*-
"""ECDSA.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1g9SO5aT0llhJ7blB0GuSRA5w2B35XDpp
"""

!pip install pycryptodome

from Crypto.Hash import SHA256
from Crypto.PublicKey import ECC
from Crypto.Signature import DSS
import rsa

#Creacion de llaves en archivos pem
privateK = ECC.generate(curve='P-256')
publicK = privateK.public_key()


message = b'I give my permission to order #4355'
#key = ECC.import_key(privateK)
h = SHA256.new(message)
signer = DSS.new(privateK, 'fips-186-3')
signature = signer.sign(h)

h = SHA256.new(message)
verifier = DSS.new(publicK, 'fips-186-3')
try:
    verifier.verify(h, signature)
    print ("The message is authentic.")
except ValueError:
    print ("The message is not authentic.")